// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OVB.Project.Eschody.Monolithic.Infrascructure.Data;

#nullable disable

namespace OVB.Project.Eschody.Monolithic.WebView.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OVB.Project.Eschody.Monolithic.Domain.AccountContext.DataTransferObject.Account", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Password");

                    b.Property<string>("TypeAccount")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("TypeAccount");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Username");

                    b.HasKey("Identifier")
                        .HasName("PK_ACCOUNT_IDENTIFIER");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK_ACCOUNT_EMAIL");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("UK_ACCOUNT_IDENTIFIER");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UK_ACCOUNT_USERNAME");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("OVB.Project.Eschody.Monolithic.Domain.AssignmentContext.DataTransferObject.Assignment", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByIdentifier")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("DATE");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TypeStatusAssignment")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Status");

                    b.HasKey("Identifier")
                        .HasName("PK_ASSIGNMENT_IDENTIFIER");

                    b.HasIndex("CreatedByIdentifier");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("UK_ASSIGNMENT_IDENTIFIER");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("OVB.Project.Eschody.Monolithic.Domain.AssignmentContext.DataTransferObject.Assignment", b =>
                {
                    b.HasOne("OVB.Project.Eschody.Monolithic.Domain.AccountContext.DataTransferObject.Account", "CreatedBy")
                        .WithMany("Assignments")
                        .HasForeignKey("CreatedByIdentifier")
                        .HasConstraintName("FK_ASSIGNMENTS_ACCOUNT");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("OVB.Project.Eschody.Monolithic.Domain.AccountContext.DataTransferObject.Account", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
